development:
  adapter: postgresql
  encoding: utf8
  database: sample_app
  username: postgres
  password: 12345
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: sample_app
  username: postgres
  password: 12345
  host: localhost